services:
  - type: web
    name: vida-total-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: vida-total-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: vida-total-db
    plan: free
    databaseName: vidatotal
    user: vidatotal
